sudo: false
language: ruby
services:
  - docker
rvm:
  - 2.5.1
before_install:
  - wget https://apt.puppetlabs.com/puppet5-release-trusty.deb
  - dpkg -i puppet5-release-trusty.deb
  - apt-get update
  - gem install bundler
  - apt install -y pdk
script:
  - bundle exec pdqtest setup && bundle exec rake spec
